<?php
/** @var $block \Unet\SocialShare\Block\ShareTo **/
/** @var $_themeHelper \Unet\SocialShare\Helper\Data **/

$shareConfig = $block->getShareConfig();
?>

<?php if ($shareConfig && $shareConfig['twitter'] && $shareConfig['twitter']['enable']) { ?>
<!--Twitter script-->
<script>!function(d,s,id){
    var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
    if(!d.getElementById(id)){js=d.createElement(s);js.id=id;
    js.src=p+'://platform.twitter.com/widgets.js';
    fjs.parentNode.insertBefore(js,fjs);}
}(document, 'script', 'twitter-wjs');
</script>
<?php } ?>

<?php if ($shareConfig && $shareConfig['facebook'] && $shareConfig['facebook']['enable']) { ?>
<!--Facebook HTML5 script-->
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php } ?>

<?php if ($shareConfig && $shareConfig['gplus'] && $shareConfig['gplus']['enable']) { ?>
<!-- Google+ script-->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<?php } ?>

<?php if ($shareConfig && $shareConfig['pinterest'] && $shareConfig['pinterest']['enable']) { ?>
<!--Pinterest script-->
<script async defer src="//assets.pinterest.com/js/pinit.js"></script>
<?php } ?>


<div id="shareto" class="shareto" data-role="share-to-links">
    <div class="social">
        <ul class="share-list"></ul>
    </div>
</div>

<?php
    $_themeHelper = $this->helper('\Unet\SocialShare\Helper\Data');
?>
<script type="text/x-magento-init">
    {
        "[data-role=share-to-links]": {
            "socialShare" : {
                "title": "<?php /* @escapeNotVerified */ echo $_themeHelper->getTitle(); ?>",
                "image": "<?php /* @escapeNotVerified */ echo $block->getImage(); ?>",
                "url": "<?php /* @escapeNotVerified */ echo $_themeHelper->getCurrentUrl(); ?>",
                "config": <?php /* @escapeNotVerified */ echo json_encode($block->getShareConfig()); ?>
            }
        }
    }
</script>
